import "./globals.css";
import type { Metadata } from "next";

import { Footer } from "@/components/Footer";
import  Sidebar  from "@/components/SidebarMenu";


export const metadata: Metadata = {
  title: "Encyclochain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="h-[100vh]">
      <Sidebar/>
      <div className=" flex flex-col">
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
