import "./globals.css";
import type { Metadata } from "next";

import { Footer } from "@/components/Footer";
import  Sidebar  from "@/components/SidebarMenu";


export const metadata: Metadata = {
  title: "Encyclochain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="h-screen flex overflow-hidden">
        <Sidebar />
        <div className="flex-1 flex flex-col overflow-y-auto">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
