/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FaeJF9tXivI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import Image from "next/image";
import prisma from "@/lib/db";
import Link from "next/link";


export async function Choicechain() {

  const prisma_res = await prisma.chain.findMany({
    select: {
      id: true,
      title: true,
    },
  });

  return (
    <div className="mt-[5%] mb-[5%] flex w-full justify-between p-[50px] max-md:flex-wrap">
      
      {prisma_res.map((chain) => (
        <div key={chain.id} className="flex flex-col items-center gap-[20px] w-[25%] max-md:w-[40%] mb-[20px]">
           <Image src={chain.imageSrc} alt={`Logo ${chain.id}`}   className="dark:invert h-auto"
            width={185}
            height={24} /> 
          <Button className={`${chain.buttonColor} mt-4 text-white`}>Explore
          <Link href={`/${chain.title}`} >Explore</Link>
          </Button>
        </div>
      ))}
    </div>
  )
}
